#!/bin/bash

`which jar &> /dev/null`
cmdstatus=$?

if [ "$cmdstatus" == "1" ]; then
   echo "The 'jar' command could not be found. Make sure it is installed and in your path."
   echo "Likely that you may have installed the JRE but not the JDK, make sure you have"
   echo "installed the JDK."
   echo ""
   echo "On Ubuntu 16.04, try installing with: "
   echo "   sudo add-apt-repository ppa:webupd8team/java"
   echo "   sudo apt-get update"
   echo "   sudo apt-get install oracle-java8-installer"
   echo ""
   echo "Otherwise, you will need to open your IDE and load the project and build."
   exit
fi 

filename="simulator.jar"
if [ "$1" != "" ]; then
   filename=$1
fi

echo "Creating jar file: ${filename}"

src=src/simulator
resource=resource
bin=${src}
here=`pwd`
filename=${here}/${filename}
javac ${src}/*.java 2>&1 | grep -v Note

cd ${bin}/..
echo "Class-Path: ." > .manifest
echo "Main-Class: simulator.Computer" >> .manifest
echo "" >> .manifest
jar cfm ${filename} .manifest simulator/*.class ${resource}/*
rm .manifest
cd ${here}
rm ${src}/*.class
echo "Done."
